Repository UnirCs/BBDDA-PER10373-2425, pull requests merged in 2024-11, with the labels that each got.

#32 captura de pantalla base de datos mysql
  Tema_1/NestorCalderonPerez/Captura de pantalla 2024-11-02 a las 17.07.18.png
  Tema_1/NestorCalderonPerez/Captura de pantalla 2024-11-03 a las 15.47.30.png
Labels: EJERCICIO INCOMPLETO

#34 MiPrimerPullRequest
  Tema_1/Gilberto Eduardo Hernandez Guaregua/helloMySQL.png
  Tema_1/Gilberto Eduardo Hernandez Guaregua/helloOracle.png
Labels: SE NECESITAN CAMBIOS

#58 Prueba de inicio
  Tema_1/Javier_Moyano_V/HelloOracle.png
  Tema_1/Javier_Moyano_V/helloMySQL.png
Labels: SE NECESITAN CAMBIOS, EJERCICIO INCOMPLETO

#75 Ejercicio 2
  Tema_2/CiprianZica/ConsultaOracle.sql
  Tema_2/CiprianZica/ConsultasMySQL.sql
  Tema_2/CiprianZica/MySqlApplication.java
  Tema_2/CiprianZica/OracleApplication.java
Labels: PR INCORRECTA

#106 Ejercicio Tema 1
  Tema_1/Unai_Pernas_Santos/Tema 1 - MYSQL.png
  Tema_1/Unai_Pernas_Santos/Tema 1 - ORACLE.png
Labels: SE NECESITAN CAMBIOS

#101 Ejercicio Tema 1 Opcional. (corregida)
  Tema_1/Alejandro Martinez Ruiz/HelloMySQL.png
  Tema_1/Alejandro Martinez Ruiz/HelloOracle.png
Labels: PR INCORRECTA

#107 Ejercicios Tema 4 y Tema 5 Jana Montero Perales
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/.gitignore
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/README.md
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/pom.xml
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/app/MySqlApplication.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/config/HibernateMySqlConfig.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/config/LogbackConfig.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/dao/DepartmentsDao.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/dao/EmployeesDao.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/Department.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/DeptEmployee.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/DeptEmployeeId.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/DeptManager.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/DeptManagerId.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/Employee.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/Salary.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/SalaryId.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/Title.java
  Tema_4/Jana Montero Perales/bbdda-hibernate_copy/src/main/java/com/unir/model/mysql/TitleId.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/.gitignore
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/MySQL Employee API.postman_collection.json
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/README.md
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/pom.xml
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/BBDDASpringDataApplication.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/controller/CachedDepartmentController.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/controller/DepartmentController.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/controller/EmployeeController.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/data/DepartmentRepository.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/data/EmployeeRepository.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/Department.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/DeptEmp.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/DeptManager.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/Employee.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/Gender.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/Salary.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/java/com/unir/employees/model/db/Title.java
  Tema_5/Jana Montero Perales/bbdda-spring-data_copy/src/main/resources/application.yml
Labels: PR INCORRECTA
